### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by TaoSea** [PeacherMZ/RuijieWebAutoLogin#2]
找不到queryString

**Comment by PeacherMZ** [comment]
有具体报错信息吗？或者浏览器里完整的request请求看看，分析一下

**Comment by TaoSea** [comment]
其实就是找不到queryString的具体内容
![屏幕截图 2024-12-24 204822](https://github.com/user-attachments/assets/b80f036d-08e6-466d-b8f3-a277f9aa6abf)

**Comment by PeacherMZ** [comment]
好像不是这一条请求，看看有其他的请求吗？

**Comment by TaoSea** [comment]
是这个referer里的内容吗
![屏幕截图 2024-12-24 210516](https://github.com/user-attachments/assets/c211687e-a0a2-4fbf-bb21-9e8c98f63799)

**Comment by PeacherMZ** [comment]
不是的，request url结尾应该是InterFace.do?method=login类似的，不然不是登录而是在验证，里面就不会带登录信息的，得找一下method是login的请求

**Comment by PeacherMZ** [comment]
可以试一下退出登录后重新登录看看

**Comment by TaoSea** [comment]
这是重新登陆的,里面都没有
![屏幕截图 2024-12-24 211417](https://github.com/user-attachments/assets/9d6f4b3e-3040-4192-a7b8-0ee3e45518fb)

**Comment by PeacherMZ** [comment]
有没有勾上保留日志呢，可能登录瞬间会刷新掉

**Comment by TaoSea** [comment]
哦哦，现在有了，但是有用的信息只有referer里的
![屏幕截图 2024-12-24 212225](https://github.com/user-attachments/assets/f6a4798e-c5c3-43b3-aa26-488ea956d356)

**Comment by PeacherMZ** [comment]
这个请求应该是对了，信息在负载那栏里面，看看

**Comment by TaoSea** [comment]
好的好的，找到了，太感谢了！

**Comment by PeacherMZ** [comment]
不客气！有问题随时发Issue

**Comment by TaoSea** [comment]
好的好的！
